node {
    docker.image('node:lts-buster-slim').withRun('-p 3000:3000') { container ->
        env.CI = 'true'
        try {
            stage('Build') {
                echo 'Starting Build stage...'
                sh 'npm install'
            }

            stage('Test') {
                echo 'Starting Test stage...'
                sh './jenkins/scripts/test.sh'
            }

            stage('Deliver') {
                echo 'Starting Deliver stage...'
                sh './jenkins/scripts/deliver.sh'

                input message: 'Finished using the website? (Click "Proceed" to continue)'

                sh './jenkins/scripts/kill.sh'
            }
        } catch (Exception e) {
            error "Pipeline failed: ${e.getMessage()}"
        }
    }
}
